### ISSUE TITLE
Voltage 3.3V < 5V

### ISSUE THREAD

**Issue by emard** [BrettRD/CANadapter#2]
MCP2551 transciever is for 5V operation while
PMOD power is 3.3V

I'd suggest to replace 2551 with a different 
3.3V compliant transciever, usually they are
SMD don't know of any DIL pacage with 3.3V

**Comment by BrettRD** [comment]
Thanks for that,
CAN bus line voltages can vary between applications; 5V is the most common, but you do find 24V networks in the wild.
This circuit runs fully isolated so the FPGA side will be happy between 2v7~5v5 as supplied by the host processor, while the line side is powered by the line.
The MCP2515 has the 2v7 lower limit, but I'm going to try to push the raw CANtx/rx (optoisolated IO) limits below 1v8.
(I had a bad experience with a non-isolated network, magic smoke came out all over the place, all at once)

**Comment by emard** [comment]
OK then I'd suggest some small switching regulator
7-40V -> 5V so the real can will properly power the
MCP2551

also adjust some resistors, 120ohm is standard impedance
for the line
100 ohm for 3.3V side of optoisolator should be a bit larger
on 5V side...

**Comment by BrettRD** [comment]
I've added a linear reg to the schematic, it's a place-holder for now, the 78L05 will only barely drive the MCP2551.  It also needs additional spike and over-current protection.
I wasn't planning on making this a super-deluxe adapter, so I'm hesitant to build a proper SPMS on-board.
Murata make a very nice 7805-drop-in-replacement module, I haven't killed one yet.
I may just stick that footprint on.
